### ISSUE TITLE
Including an open-source license

### ISSUE THREAD

**Issue by LewisDyer** [Cynt3r/boost-treewidth#1]
Hi there - I'm a PhD student at the University of Glasgow, and I'm currently working on implementing a recent result in approximate subgraph counting using the Boost graph library. As part of that I need to implement nice tree decompositions in Boost, and your work looks perfect for that.

If you're willing to, including an open source license in the project would allow me and other researchers and developers to use your work in practice. I'd personally recommend the [Boost Software License 1.0](https://choosealicense.com/licenses/bsl-1.0/), since this is used by most of the rest of Boost. And of course, I'll happily give you credit and cite your thesis when I use your implementation.

**Comment by Cynt3r** [comment]
Hi Lewis, it seems I've forgotten to add a license when I first published the work here. This is now fixed in 619700628243a3daff617a3662deea2d15a3d372. Thank you for letting me know and also good luck on your work!
